include:
  - .gitlab-ci/job-definitions.yml
  - .gitlab-ci/global-declarations.yml
  - .gitlab-ci/devices.yml

rootfs-amd64-phosh:
  extends:
    - .rootfs-generic
    - .arch-amd64
    - .shell-phosh

rootfs-amd64-plasma-mobile:
  extends:
    - .rootfs-generic
    - .arch-amd64
    - .shell-plasma-mobile

rootfs-arm64-phosh:
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .shell-phosh

rootfs-arm64-plasma-mobile:
  extends:
    - .rootfs-generic
    - .arch-arm64
    - .shell-plasma-mobile

installfs-arm64:
  extends:
    - .rootfs-installer
    - .arch-arm64

devicefs-librem5-phosh:
  extends:
    - .devicefs
    - .device-librem5
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

devicefs-librem5-plasma-mobile:
  extends:
    - .devicefs
    - .device-librem5
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

devicefs-sunxi-phosh:
  extends:
    - .devicefs
    - .device-sunxi
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

devicefs-sunxi-plasma-mobile:
  extends:
    - .devicefs
    - .device-sunxi
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

devicefs-rockchip-phosh:
  extends:
    - .devicefs
    - .device-rockchip
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

devicefs-rockchip-plasma-mobile:
  extends:
    - .devicefs
    - .device-rockchip
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-sunxi-phosh:
  extends:
    - .image
    - .device-sunxi
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-sunxi-plasma-mobile:
  extends:
    - .image
    - .device-sunxi
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-rockchip-phosh:
  extends:
    - .image
    - .device-rockchip
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-rockchip-plasma-mobile:
  extends:
    - .image
    - .device-rockchip
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-librem5-phosh:
  extends:
    - .image
    - .device-librem5
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-librem5-plasma-mobile:
  extends:
    - .image
    - .device-librem5
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-qcom-phosh:
  extends:
    - .image
    - .device-qcom
    - .shell-phosh
  needs:
    - rootfs-arm64-phosh

image-qcom-plasma-mobile:
  extends:
    - .image
    - .device-qcom
    - .shell-plasma-mobile
  needs:
    - rootfs-arm64-plasma-mobile

image-amd64-phosh:
  extends:
    - .image
    - .device-amd64
    - .shell-phosh
  needs:
    - rootfs-amd64-phosh

image-amd64-plasma-mobile:
  extends:
    - .image
    - .device-amd64
    - .shell-plasma-mobile
  needs:
    - rootfs-amd64-plasma-mobile

installer-librem5-phosh:
  extends:
    - .installer
    - .device-librem5
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-librem5-phosh

installer-librem5-plasma-mobile:
  extends:
    - .installer
    - .device-librem5
    - .shell-plasma-mobile
  needs:
    - installfs-arm64
    - devicefs-librem5-plasma-mobile

installer-sunxi-phosh:
  extends:
    - .installer
    - .device-sunxi
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-sunxi-phosh

installer-sunxi-plasma-mobile:
  extends:
    - .installer
    - .device-sunxi
    - .shell-plasma-mobile
  needs:
    - installfs-arm64
    - devicefs-sunxi-plasma-mobile

installer-rockchip-phosh:
  extends:
    - .installer
    - .device-rockchip
    - .shell-phosh
  needs:
    - installfs-arm64
    - devicefs-rockchip-phosh

installer-rockchip-plasma-mobile:
  extends:
    - .installer
    - .device-rockchip
    - .shell-plasma-mobile
  needs:
    - installfs-arm64
    - devicefs-rockchip-plasma-mobile
